"""add_products_table

Revision ID: 06e3faa1ddbe
Revises: 0728403a6f98
Create Date: 2026-07-06 12:00:22.207049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06e3faa1ddbe'
down_revision: Union[str, Sequence[str], None] = '0728403a6f98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('product_number', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('dimensions', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=True),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.Column('rack_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rack_id'], ['warehouse_racks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['warehouse_sections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_company_id'), 'products', ['company_id'], unique=False)
    op.create_index(op.f('ix_products_product_number'), 'products', ['product_number'], unique=False)
    op.add_column('shipment_items', sa.Column('product_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'shipment_items', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipment_items', type_='foreignkey')
    op.drop_column('shipment_items', 'product_id')
    op.drop_index(op.f('ix_products_product_number'), table_name='products')
    op.drop_index(op.f('ix_products_company_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
