"""add_einvoice_and_eway_compliance

Revision ID: 0728403a6f98
Revises: baaf773bdf02
Create Date: 2026-07-04 16:18:07.480901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0728403a6f98'
down_revision: Union[str, Sequence[str], None] = 'baaf773bdf02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('e_invoices',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('irn', sa.String(length=64), nullable=False),
    sa.Column('ack_no', sa.String(length=50), nullable=False),
    sa.Column('ack_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('signed_invoice', sa.Text(), nullable=False),
    sa.Column('signed_qr_code', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id')
    )
    op.create_index(op.f('ix_e_invoices_irn'), 'e_invoices', ['irn'], unique=True)
    op.add_column('companies', sa.Column('is_e_invoice_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('eway_bills', sa.Column('from_pincode', sa.String(length=6), nullable=True))
    op.add_column('eway_bills', sa.Column('to_pincode', sa.String(length=6), nullable=True))
    op.add_column('eway_bills', sa.Column('supply_type', sa.String(length=10), nullable=True))
    op.add_column('eway_bills', sa.Column('sub_supply_type', sa.String(length=20), nullable=True))
    op.add_column('eway_bills', sa.Column('doc_type', sa.String(length=20), nullable=True))
    op.add_column('eway_bills', sa.Column('doc_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('eway_bills', sa.Column('trans_mode', sa.String(length=15), nullable=True))
    op.add_column('eway_bills', sa.Column('uqc_code', sa.String(length=10), nullable=True))
    op.add_column('eway_bills', sa.Column('vehicle_type', sa.String(length=10), nullable=True))
    op.add_column('eway_bills', sa.Column('trans_doc_no', sa.String(length=50), nullable=True))
    op.add_column('eway_bills', sa.Column('trans_doc_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('eway_bills', sa.Column('cess_non_advol_value', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('eway_bills', sa.Column('other_value', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('eway_bills', sa.Column('total_value', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('eway_bills', sa.Column('cgst_value', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('eway_bills', sa.Column('sgst_value', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('eway_bills', sa.Column('igst_value', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('eway_bills', sa.Column('cess_value', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('eway_bills', sa.Column('tot_inv_value', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eway_bills', 'tot_inv_value')
    op.drop_column('eway_bills', 'cess_value')
    op.drop_column('eway_bills', 'igst_value')
    op.drop_column('eway_bills', 'sgst_value')
    op.drop_column('eway_bills', 'cgst_value')
    op.drop_column('eway_bills', 'total_value')
    op.drop_column('eway_bills', 'other_value')
    op.drop_column('eway_bills', 'cess_non_advol_value')
    op.drop_column('eway_bills', 'trans_doc_date')
    op.drop_column('eway_bills', 'trans_doc_no')
    op.drop_column('eway_bills', 'vehicle_type')
    op.drop_column('eway_bills', 'uqc_code')
    op.drop_column('eway_bills', 'trans_mode')
    op.drop_column('eway_bills', 'doc_date')
    op.drop_column('eway_bills', 'doc_type')
    op.drop_column('eway_bills', 'sub_supply_type')
    op.drop_column('eway_bills', 'supply_type')
    op.drop_column('eway_bills', 'to_pincode')
    op.drop_column('eway_bills', 'from_pincode')
    op.drop_column('companies', 'is_e_invoice_enabled')
    op.drop_index(op.f('ix_e_invoices_irn'), table_name='e_invoices')
    op.drop_table('e_invoices')
    # ### end Alembic commands ###
