"""add performance indexes

Revision ID: 5e74665588ed
Revises: 8908056749b0
Create Date: 2026-07-04 10:54:54.994607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e74665588ed'
down_revision: Union[str, Sequence[str], None] = '8908056749b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('drivers_license_number_key'), 'drivers', type_='unique')
    op.drop_constraint(op.f('drivers_user_id_key'), 'drivers', type_='unique')
    op.create_index(op.f('ix_drivers_assigned_vehicle_id'), 'drivers', ['assigned_vehicle_id'], unique=False)
    op.create_index(op.f('ix_drivers_license_number'), 'drivers', ['license_number'], unique=True)
    op.create_index(op.f('ix_drivers_status'), 'drivers', ['status'], unique=False)
    op.create_index(op.f('ix_drivers_user_id'), 'drivers', ['user_id'], unique=True)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('ix_shipment_items_shipment_id'), 'shipment_items', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_shipment_tracking_shipment_id'), 'shipment_tracking', ['shipment_id'], unique=False)
    op.drop_constraint(op.f('shipments_tracking_number_key'), 'shipments', type_='unique')
    op.create_index(op.f('ix_shipments_company_id'), 'shipments', ['company_id'], unique=False)
    op.create_index(op.f('ix_shipments_customer_id'), 'shipments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_shipments_driver_id'), 'shipments', ['driver_id'], unique=False)
    op.create_index(op.f('ix_shipments_status'), 'shipments', ['status'], unique=False)
    op.create_index(op.f('ix_shipments_tracking_number'), 'shipments', ['tracking_number'], unique=True)
    op.create_index(op.f('ix_shipments_warehouse_id'), 'shipments', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.drop_constraint(op.f('vehicles_registration_number_key'), 'vehicles', type_='unique')
    op.create_index(op.f('ix_vehicles_company_id'), 'vehicles', ['company_id'], unique=False)
    op.create_index(op.f('ix_vehicles_registration_number'), 'vehicles', ['registration_number'], unique=True)
    op.create_index(op.f('ix_vehicles_status'), 'vehicles', ['status'], unique=False)
    op.create_index(op.f('ix_warehouse_racks_section_id'), 'warehouse_racks', ['section_id'], unique=False)
    op.create_index(op.f('ix_warehouse_sections_warehouse_id'), 'warehouse_sections', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_warehouses_company_id'), 'warehouses', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warehouses_company_id'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouse_sections_warehouse_id'), table_name='warehouse_sections')
    op.drop_index(op.f('ix_warehouse_racks_section_id'), table_name='warehouse_racks')
    op.drop_index(op.f('ix_vehicles_status'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_registration_number'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_company_id'), table_name='vehicles')
    op.create_unique_constraint(op.f('vehicles_registration_number_key'), 'vehicles', ['registration_number'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_index(op.f('ix_shipments_warehouse_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_tracking_number'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_status'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_driver_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_customer_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_company_id'), table_name='shipments')
    op.create_unique_constraint(op.f('shipments_tracking_number_key'), 'shipments', ['tracking_number'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_shipment_tracking_shipment_id'), table_name='shipment_tracking')
    op.drop_index(op.f('ix_shipment_items_shipment_id'), table_name='shipment_items')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_drivers_user_id'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_status'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_license_number'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_assigned_vehicle_id'), table_name='drivers')
    op.create_unique_constraint(op.f('drivers_user_id_key'), 'drivers', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('drivers_license_number_key'), 'drivers', ['license_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
