"""add status to shipment items

Revision ID: 8908056749b0
Revises: 9ba332e54fc3
Create Date: 2026-07-04 02:28:59.777570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8908056749b0'
down_revision: Union[str, Sequence[str], None] = '9ba332e54fc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipment_items', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipment_items', 'status')
    # ### end Alembic commands ###
