"""add_company_details

Revision ID: 9d678053ccd0
Revises: 2ee4043b9e50
Create Date: 2026-07-03 16:16:05.419389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d678053ccd0'
down_revision: Union[str, Sequence[str], None] = '2ee4043b9e50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('support_email', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('invoice_prefix', sa.String(length=50), server_default='INV', nullable=False))
    op.add_column('companies', sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), server_default='18.00', nullable=False))
    op.add_column('companies', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'address')
    op.drop_column('companies', 'tax_rate')
    op.drop_column('companies', 'invoice_prefix')
    op.drop_column('companies', 'support_email')
    # ### end Alembic commands ###
